<img src="images/a.webp" />

<img src="images/filter1.gif" />

<img src="images/filter2.gif" />

<img src="images/filter3.gif" />

<img src="images/filter4.gif" />

<img src="images/filter5.gif" />

##### 원이미지와 kernel(filter)를 convolution 하려는데 가상에는 데이터가 부족해서 0을 추가해야 하므로 이것을 zeros padding이라함.
- convolution: 이동하면서 내적함

0패딩 말고 인접한 데이터를 padding 할 수 있음.

<img src="images/convolution.png" />

<img src="images/convolution.gif" />

<img src="images/equation1.png" />

<img src="images/equation2.png" />

<img src="images/20231023_130002_458.jpg" />

In [1]:
import numpy as np
image = np.array([[-1,1,0,1,0],[-1,3,1,2,5],[-1,2,5,6,7],[8,-1,1,0,1],[-1,0,0,1,0]])
filtered  = np.array([[-1,0,1],[0,1,0],[0,1,1]])
# 2개의 신호를 convolution하세요
image.shape, filtered.shape

((5, 5), (3, 3))

In [2]:
# 이것을 노가다로 만들어볼 것
from scipy.signal import convolve2d
flt_img = convolve2d(image, filtered, mode='same')
flt_img

array([[-4, -1,  1, -3,  2],
       [-4, -3, -2,  1, 12],
       [-1, 11,  8,  9, 14],
       [ 7, -1,  7, 11, 15],
       [ 7,  7,  0,  2,  1]])

<a href="https://m.blog.naver.com/wideeyed/221665256911">[Numpy] 1차원 또는 2차원 패딩</a>

In [3]:
import numpy as np
image = np.array([[-1,1,0,1,0],[-1,3,1,2,5],[-1,2,5,6,7],[8,-1,1,0,1],[-1,0,0,1,0]])
filtered  = np.array([[-1,0,1],[0,1,0],[0,1,1]])
# 2개의 신호를 convolution하세요
image.shape, filtered.shape

((5, 5), (3, 3))

In [4]:
# 상하좌우 모두 2개 행/열 0으로 패딩합니다
np.pad(image, ((1,1),(1,1)), 'constant', constant_values=0)

array([[ 0,  0,  0,  0,  0,  0,  0],
       [ 0, -1,  1,  0,  1,  0,  0],
       [ 0, -1,  3,  1,  2,  5,  0],
       [ 0, -1,  2,  5,  6,  7,  0],
       [ 0,  8, -1,  1,  0,  1,  0],
       [ 0, -1,  0,  0,  1,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0]])

In [5]:
padded_image = []
padded_zero = np.array([0 for i in range(5)]) # 5개를 0으로 만들다
padded_image.append(padded_zero) # 첫번째 행에 0을 추가
for i in image:
    padded_image.append(i) # image를 다 추가
padded_image.append(padded_zero) # 마지막 행에 0을 추가
transposed_first = np.array(padded_image)
padded_zero = np.array([0 for i in range(7)]) # 7개를 0으로 만든다.
copyed = np.array([padded_zero, *transposed_first.T, padded_zero]) # *transposed_first.T 세로에 0 추가
padded_image = copyed.T # 다시 원래대로 돌리기 위해 transpose 해서 복원
padded_image

array([[ 0,  0,  0,  0,  0,  0,  0],
       [ 0, -1,  1,  0,  1,  0,  0],
       [ 0, -1,  3,  1,  2,  5,  0],
       [ 0, -1,  2,  5,  6,  7,  0],
       [ 0,  8, -1,  1,  0,  1,  0],
       [ 0, -1,  0,  0,  1,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0]])

In [6]:
convolved = []
for j in range(5):
    convolved.append([sum(sum(np.multiply(padded_image[i:i+3, j:j+3], filtered))) for i in range(5) ])
convolved

[[1, 1, 9, 9, -2],
 [5, 11, 4, 5, -7],
 [3, 12, 5, 6, 1],
 [8, 15, 11, 3, 1],
 [5, 11, 6, -5, 0]]

<img src="images/공식.jpg" />

<img src="images/filter6.jpg" />

<img src="images/filter7.jpg" />

<a href="https://velog.io/@se0yeon00/%EC%98%81%EC%83%81%EC%8B%A0%ED%98%B8%EC%B2%98%EB%A6%AC">영상 신호 처리 필터</a>

<a href="https://programmingfbf7290.tistory.com/entry/%EC%A3%BC%ED%8C%8C%EC%88%98-%EC%98%81%EC%97%AD-%EC%98%81%EC%83%81-%ED%95%84%ED%84%B0%EA%B0%80%EC%9A%B0%EC%8B%9C%EC%95%88-%EC%A3%BC%ED%8C%8C%EC%88%98-%ED%95%84%ED%84%B0">영상 신호 처리 가우시안</a>

<a href="https://junstar92.tistory.com/405">영상 신호 처리 가우시안</a>

In [7]:
import cv2
import numpy as np

In [17]:
def prepocessing(image):
    image = cv2.imread(image)
    image = cv2.cvtColor(src=image, code=cv2.COLOR_BGR2GRAY)
    return image

In [18]:
def convolve2D(image, kernel, padding=0, strides=1):
    # kernel = fliter, stride=> 몇칸씩 이동하면서 convolution할지 결정
    kernel = np.flipud(np.fliplr(kernel)) # left right(수평뒤집기), up -> down(수직뒤집기, )
    # 이미지와 kernel의 shape을 구함
    xKernelShape = kernel.shape[0]
    yKernelShape = kernel.shape[1]
    xImageShape = image.shape[0]
    yImageShape = image.shape[1]
    # 각각의 출력 차원을 크기 공식을 적용하여 구할 수 있음
    xOutput = int(((xImageShape - xKernelShape + 2*padding) / strides) + 1) # 위의 공식
    yOutput = int(((yImageShape - yKernelShape + 2*padding) / strides) + 1)
    output = np.zeros((xOutput, yOutput))
    if padding != 0:
        imagePadded = np.zeros((image.shape[0] + padding*2, image.shape[1] + padding*2))
        # padded 이미지의 내부는 실제 이미지로 대체함 (slicing 사용하여)
        imagePadded[int(padding):int(-1*padding), int(padding):int(-1*padding)] = image
    else: # padding이 없다면
        imagepadded = image
    for y in range(image.shape[1]): # 반복하면서 이미지의 크기보다
        if y > image.shape[1] - yKernelShape: break
        if y % strides == 0: # 특정 stride만큼 내려갈 때만 convolution함
            for x in range(image.shape[0]):
                # 커널의 경계를 벗어나면 다음 행으로 이동
                if x > image.shape[0] - xKernelShape: break
                try:
                    if x % strides == 0: # x의 값이 strides의 배수가 될 때만
                        # 특정 stride로 이동할 때만 convolution함
                        output[x, y] = (kernel * imagePadded[x:x+xKernelShape, y:y+yKernelShape]).sum()
                except:
                    break
    return output

In [10]:
kernel = np.array([[1/16,1/8,1/16], [1/8,1/4,1/8], [1/16, 1/8, 1/16]])

image = prepocessing('images/lenna.bmp')
print(image.shape)
output = convolve2D(image, kernel, padding=2)
cv2.imwrite('2Dconvolved.jpg', output)

(512, 512)


True

In [11]:
kernel = np.array([[-1,-1,-1],[-1,8,-1],[-1,-1,-1]])

image = prepocessing('images/lenna.bmp')
print(image.shape)
output = convolve2D(image, kernel, padding=2)
cv2.imwrite('2Dconvolved.jpg', output)

(512, 512)


True

In [12]:
kernel = np.array([[-1,-1,-1,-1,-1],[-1,-1,-1,-1,-1],[-1,-1,24,-1,-1],
                   [-1,-1,-1,-1,-1],[-1,-1,-1,-1,-1]])

image = prepocessing('images/lenna.bmp')
print(image.shape)
output = convolve2D(image, kernel, padding=2)
cv2.imwrite('2Dconvolved5x.jpg', output)

(512, 512)


True

In [13]:
kernel_blur3 = np.array([[1/16,1/8,1/16], [1/8,1/4,1/8], [1/16, 1/8, 1/16]])
kernel_3x = np.array([[-1,-1,-1,-1,-1],[-1,-1,-1,-1,-1],[-1,-1,24,-1,-1],
                   ])
kernel_5x = np.array([[-1,-1,-1,-1,-1],[-1,-1,-1,-1,-1],[-1,-1,24,-1,-1],
                   [-1,-1,-1,-1,-1],[-1,-1,-1,-1,-1]])
kernel_7x = np.array([[-1,-1,-1,-1,-1],[-1,-1,-1,-1,-1],[-1,-1,24,-1,-1],
                   [-1,-1,-1,-1,-1],[-1,-1,-1,-1,-1],
                   [-1,-1,-1,-1,-1],[-1,-1,-1,-1,-1]])
gaussian_filter_5x5 = np.array([
    [1/256, 4/256, 6/256, 4/256, 1/256],
    [4/256, 16/256, 24/256, 16/256, 4/256],
    [6/256, 24/256, 36/256, 24/256, 6/256],
    [4/256, 16/256, 24/256, 16/256, 4/256],
    [1/256, 4/256, 6/256, 4/256, 1/256]
])

list_kernel = [kernel_3x, kernel_5x ,kernel_7x, kernel_blur3, gaussian_filter_5x5]
image = prepocessing('images/lenna.bmp')
print(image.shape)
for idx, i in enumerate(list_kernel):
    output = convolve2D(image, i, padding=2)
    cv2.imwrite('2Dconvolved5x_' + str(idx) + '.jpg', output)

(512, 512)


In [19]:
kernel_1x = np.array([[-1,-1,-1],[-1,8,-1],[-1,-1,-1] ])
kernel_2x = np.array([[-1,-1,-1],[2,2,2],[-1,-1,-1] ])
kernel_3x = np.array([[-1,0,-1],[-1,0,-1],[-1,0,-1] ])

list_kernel = [kernel_1x, kernel_2x, kernel_3x]
image = prepocessing('images/20231023_173739_134.jpg')
print(image.shape)
for idx, i in enumerate(list_kernel):
    output = convolve2D(image, i, padding=2)
    cv2.imwrite('2Dconvolved5x_' + str(idx) + '.jpg', output)

(246, 545)


In [21]:
kernel_1x = np.array([[-1,-1,-1],[-1,8,-1],[-1,-1,-1] ])
kernel_2x = np.array([[-1,-1,-1],[2,2,2],[-1,-1,-1] ])
kernel_3x = np.array([[-1,0,-1],[-1,0,-1],[-1,0,-1] ])

list_kernel = [kernel_1x, kernel_2x, kernel_3x]
image = prepocessing('images/cross.jpg')
print(image.shape)
for idx, i in enumerate(list_kernel):
    output = convolve2D(image, i, padding=2)
    cv2.imwrite('2Dconvolved5x_' + str(idx) + '.jpg', output)

(771, 1000)


In [22]:
kernel_1x = np.array([[-1,-1,-1],[-1,8,-1],[-1,-1,-1] ])
kernel_2x = np.array([[-1,-1,-1],[2,2,2],[-1,-1,-1] ])
kernel_3x = np.array([[-1,0,-1],[-1,0,-1],[-1,0,-1] ])

list_kernel = [kernel_1x, kernel_2x, kernel_3x]
image = prepocessing('images/vertical.jpg')
print(image.shape)
for idx, i in enumerate(list_kernel):
    output = convolve2D(image, i, padding=2)
    cv2.imwrite('2Dconvolved5x_' + str(idx) + '.jpg', output)

(600, 1000)
