# 변화율 Rate of Change
Functions are often visualized as a line on a graph, and this line shows how the value returned by the function changes based on changes in the input value.

## 선형 변화율 Linear Rate of Change

For example, imagine a function that returns the number of meters travelled by a cyclist based on the number of seconds that the cyclist has been cycling.

Here is such a function:

\begin{equation}q(x) = 2x + 1\end{equation}

We can plot the output for this function for a period of 10 seconds like this:

In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
def q(x):
    return 2*x + 1

In [ ]:
x = np.array(range(0,11)) #  0~10까지의 x변수의 배열 생성

In [ ]:
plt.xlabel('Second')
plt.ylabel('Meters')
plt.xticks(range(0,11,1))
plt.yticks(range(0,22,1))
plt.grid()
plt.plot(x,q(x), color='green')
plt.show()

It's clear from the graph that ***q*** is a *linear* function that describes a slope in which distance increases at a constant rate over time. In other words, the cyclist is travelling at a constant speed.

But what speed? 속도는 얼마?

Speed, or more technically, velocity is a measure of change - 시간이 흐르면서 얼마나 이동했는지의 평가 수단 (which is why we typically express it as a unit of distance per a unit of time, like *시간 당 마일* or *시간 당 미터*). So we're looking for a way to measure the change in the line created by the function.

The change in values along the line define its *slope*, which we know from a previous lesson is represented like this:

\begin{equation}m = \frac{\Delta{y}}{\Delta{x}} \end{equation} 

함수의 기울기(slope)를 계산 가능 

\begin{equation}m = \frac{q(x_{2}) - q(x_{1})}{x_{2} - x_{1}} \end{equation}

이 수식을 적용하기 위해 우리의 직선으로부터 3개의 순서쌍 ***x*** and ***q(x)***

- 1초 후 ***x*** 는 1 에서의 함수값 ***q***(1) = **3**.
- 10초 후 ***x*** 는 10 에서의 함수값 ***q***(10) = 21.

So we can meassure the rate of change like this:

\begin{equation}m = \frac{21 - 3}{10 - 1} \rightarrow 평균변화율 \end{equation}
$$ \Delta가 -0으로 근사하면 그 순간에서의 순간변화율(진짜 미분) $$
This is the same as:

\begin{equation}m = \frac{18}{9} \end{equation}

아래와 같이 단순화 가능

\begin{equation}m = \frac{2}{1} \end{equation}

So our rate of change is <sup>2</sup>/<sub>1</sub> or put another way, the cyclist is travelling at 2 meters-per-second.

## 평균 변화율 Average Rate of Change
주어진 시간동안 이동한 거리의 또다른 함수를 보자

\begin{equation}r(x) = x^{2} + x\end{equation}

파이썬으로 구현

In [ ]:
x = np.arange(-10,11) #  0~10까지의 x변수의 배열 생성

In [ ]:
def r1(x):
    return x**2 + x
plt.xlabel('Second')
plt.ylabel('Meters')
plt.xticks(np.arange(-10,11,1))
# plt.yticks(range(0,22,1))
plt.grid()
plt.plot(x,r1(x), color='green')
plt.show()
# 파이썬 코드를 x의 값이 -1/2일 때의 y값을 구하세요 

In [ ]:
# 최소점
def r2(x):
    return x**2 + 2*x + 5
# (x+1)^2 -1 +5
plt.xlabel('Second')
plt.ylabel('Meters')
plt.xticks(np.arange(-10,11,1))
# plt.yticks(range(0,22,1))
plt.grid()
plt.plot(x,r2(x), color='green')
plt.show()
# 파이썬 코드를 x의 값이 -1/2일 때의 y값을 구하세요 


In [ ]:
# 최대점
def r3(x):
    return -x**2 - 4*x -2
plt.xlabel('Second')
plt.ylabel('Meters')
plt.xticks(np.arange(-10,11,1))
# plt.yticks(range(0,22,1))
plt.grid()
plt.plot(x,r3(x), color='green')
plt.show()
# 파이썬 코드를 x의 값이 -1/2일 때의 y값을 구하세요 

In [18]:
from sympy import *
import numpy as np
a, b, c = symbols('a b c')

In [ ]:
funcs = [str(np.random.randint(10)) + 
         '*x**2+' + str(np.random.randint(10)) + '*x+' + str(np.random.randint(100))
        for _ in range(5) ]

In [ ]:
for i in funcs:
    print(i)

In [ ]:
[solve(i) for i in funcs][0][0]

In [ ]:
[solve(expand(i)) for i in funcs]

$$ b^{2} - 4ac > 0보다 커야 함 $$

$$ y = f(x) = ax^{2} + bx + c $$

$$ \frac{-b \pm \sqrt{b^{2}-4ac}}{2a} $$

In [ ]:
위의 근의 공식을 함수로 정의하고 b**2-4*a*c가 0보다 같거나 클때만 값을 반환함

In [2]:
def solve_root_fn(a, b, c):
    test = b**2 - 4*a*c
    if  test < 0: return 
    return np.array([-b + np.sqrt(test),-b - np.sqrt(test)])/(2*a)
    
solve_root_fn(2,13,4)

array([-0.32382502, -6.17617498])

In [ ]:
ckeck_result = lambda x : 8*x**2+86*x+95
print(ckeck_result(-1.25))
print(ckeck_result(-9.5))

In [ ]:
for i in range(100):
    a_ = np.random.randint(1,100)
    b_ = np.random.randint(1,100)
    c_ = np.random.randint(1,100)
    print(solve_root_fn(a_, b_, c_), root_solve_sympy(a_,b_,c_) )

In [ ]:
for i in range(100):
    a_ = np.random.randint(1,100)
    b_ = np.random.randint(1,100)
    c_ = np.random.randint(1,100)
    print(solve_root_fn(a_, b_, c_), solve(root_solve_sympy(a_,b_,c_)) )

In [ ]:
user_def = [-0.10481505, -0.77356333]
symp_def = [-65/148 - np.sqrt(2449)/148, -65/148 + np.sqrt(2449)/148]
abs(user_def[0] - symp_def[0]) < 10

In [52]:
final_result = []
for i in range(100):
    a_ = np.random.randint(1,100)
    b_ = np.random.randint(1,100)
    c_ = np.random.randint(1,100)
    final_result.append((solve_root_fn(a_, b_, c_), root_solve_sympy(a_,b_,c_) ))
a_1 = [i for i in final_result if i[0] is not None][1][1][0]
b_1 = [i for i in final_result if i[0] is not None][1][1][1]
a_0 = [i for i in final_result if i[0] is not None][1][0][0]
b_0 = [i for i in final_result if i[0] is not None][1][0][1]
result = (a_1 + b_1) - (a_0 + b_0)
print(result)

0


In [ ]:
def f(x):
    return 2*x**2 + 4*x + 87

In [ ]:
[solve(i) for i in funcs][0][0]

In [ ]:
# 3x^2 + 16x + 4
x = Symbol('x')
solve(3*x**2 + 16*x + 4)

In [ ]:
factor(3*x**2 + 16*x + 4)

In [ ]:
def sangjun_solve(a, b, c):
    num = (b**2) - (4*a*c)
    if num > 0:
        r1 = (-b + (b**2-4*a*c)**0.5)/(2*a)
        r2 = (-b - (b**2-4*a*c)**0.5)/(2*a)
        print("{} 또는 {} 입니다.".format(r1,r2))
    elif num == 0:
        x = -b / 2*a
        print("중근이고, 해는 {} 입니다".format(x))
    else:
        r1 = (-b + (b**2-4*a*c)**0.5)/(2*a)
        r2 = (-b - (b**2-4*a*c)**0.5)/(2*a)
        print("허근이며, 해는 {} 또는 {} 입니다".format(r1,r2))
        
a = 3
b = 16
c = 4
sangjun_solve(a,b,c)

In [ ]:
f = x**2 + 2*x + 1

In [ ]:
solve(f)

In [3]:
def root_solve_sympy(a, b, c):
    str1 = ''
    a_str = str(a)
    b_str = str(b)
    c_str = str(c)
    str1 += a_str + '*x**2+' + b_str + '*x+' + c_str
    if b**2 - 4*a*c >= 0: return str1
    else: return None

In [ ]:
result_with_none = [root_solve_sympy(np.random.randint(10)
                , np.random.randint(10)
                , np.random.randint(100) ) for _ in range(100)]
result_without_none = [i for i in result_with_none if i is not None]
result_without_none

In [ ]:
result_with_none = [root_solve() for _ in range(100)]
result_witout_none = [i for i in result_with_none if i is not None]
result_witout_none

In [ ]:
[solve(f) for f in result_witout_none]

In [69]:
# 계산해서 해 구하기
def solve_root_fn(a, b, c):
    test = b**2 - 4*a*c
    if  test < 0: return
    return np.array([-b - np.sqrt(test),-b + np.sqrt(test)])/(2*a)

In [70]:
# sympy로 해 구하기
def root_solve_sympy(a, b, c):
    str1 = ''
    a_str = str(a)
    b_str = str(b)
    c_str = str(c)
    str1 += a_str + '*x**2+' + b_str + '*x+' + c_str
    if b**2 - 4*a*c >= 0: return solve(str1)
    else: return None

In [71]:
final_result = []
for i in range(100):
    a_ = np.random.randint(-100,100)
    b_ = np.random.randint(-100,100)
    c_ = np.random.randint(-100,100)
    final_result.append((solve_root_fn(a_, b_, c_), root_solve_sympy(a_,b_,c_) ))
# final_result: None이 아닌 해의 결과만 필터링하여 저장
final_result_filter = [ i for i in final_result if i[0] is not None]
final_result_filter

[(array([0.09459927, 1.24363603]),
  [91/136 - sqrt(6105)/136, sqrt(6105)/136 + 91/136]),
 (array([-0.24427268, -5.21027278]),
  [-30/11 - sqrt(746)/11, -30/11 + sqrt(746)/11]),
 (array([ 0.51996205, -1.51996205]),
  [-1/2 + sqrt(3999)/62, -sqrt(3999)/62 - 1/2]),
 (array([-1.71660022,  0.84563248]),
  [-27/62 + 3*sqrt(701)/62, -3*sqrt(701)/62 - 27/62]),
 (array([-2.35193455,  0.4449578 ]),
  [-41/43 + 4*sqrt(226)/43, -4*sqrt(226)/43 - 41/43]),
 (array([ 1.84889689, -0.97134587]),
  [43/98 - 13*sqrt(113)/98, 43/98 + 13*sqrt(113)/98]),
 (array([-3.21078722,  1.74412056]),
  [-11/15 + sqrt(1381)/15, -sqrt(1381)/15 - 11/15]),
 (array([-4.61926505, -0.44740162]),
  [-38/15 - sqrt(979)/15, -38/15 + sqrt(979)/15]),
 (array([ 0.13843424, -0.69162573]),
  [-13/47 + sqrt(1522)/94, -sqrt(1522)/94 - 13/47]),
 (array([ 0.22662813, -0.92662813]),
  [-7/20 + sqrt(133)/20, -sqrt(133)/20 - 7/20]),
 (array([ 0.32766236, -1.1738162 ]),
  [-11/26 + sqrt(381)/26, -sqrt(381)/26 - 11/26]),
 (array([-1.095612

In [72]:
# 합의 차이가 1 미만인 경우 False
sum([False for i,j in final_result_filter if abs(sum(i)-sum(j)) < 1 ])

0

In [73]:
for i in final_result_filter:
    first = abs(i[0][0] - i[1][0])
    second = abs(i[0][1] - i[1][1])
    print(first + second < 100)

True
True
True
True
True
True
True
True
True
True
True
True
False
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True


In [59]:
def f():
    return 1
def g():
    return 1

In [65]:
b = []
b.append((f(),g()))
b

[(1, 1)]