# 선형대수

<div>
    <table style="float: left;">
        <tr></tr>
        <tr><th style="text-align: center;">넘파이</th></tr>
        <tr><td style="text-align: center;">N차원 배열 객체(ndarray)</td></tr>
        <tr><td style="text-align: center;">연속 원소 배열 생성 함수</td></tr>
        <tr><td style="text-align: center;">배열 생성 함수</td></tr>
        <tr><td style="text-align: center;">인덱싱(Indexing) & 슬라이싱(Slicing)</td></tr>
    </table>
    <table style="float: left;">
        <tr><th style="text-align: center;">선형대수</th></tr>
        <tr><td style="text-align: center;">벡터</td></tr>
        <tr><td style="text-align: center;">행렬</td></tr>
        <tr><td style="text-align: center;">선형결합</td></tr>
    </table>
        <table style="float: left;">
        <tr></tr>
        <tr><th style="text-align: center;">인공 신경망</th></tr>
        <tr><td style="text-align: center;">가중치</td></tr>
        <tr><td style="text-align: center;">편향</td></tr>
        <tr><td style="text-align: center;">데이터 세트</td></tr>
        <tr><td style="text-align: center;">경사 하강법</td></tr>
    </table>
</div>

# 넘파이

In [1]:
A = [1,2,3]
B = [1,2,3]
# A * B 연산 안 됨

import numpy as np
A = np.array([1,2,3])
B = np.array([1,2,3])
A * B # 벡터라이제이션(vectorization): 대응하는 성분끼리 연산함(element-wise)

array([1, 4, 9])

### 넘파이 배열(N차원 배열 객체(ndarray))
    : 모든 원소는 같은 타입, 같은 크기를 가지며, 차원 개수만큼의 정수로 인덱싱됨.
- 차원(demension) = 축(axis)

In [2]:
A = np.array([0.1, 0.2, 0.3])
print('A.dtype:', A.dtype)
print('type(A):', type(A))
print('type(A[0]):', type(A[0]))

A.dtype: float64
type(A): <class 'numpy.ndarray'>
type(A[0]): <class 'numpy.float64'>


In [3]:
# 미리 생성한 리스트를 사용하여 넘파이 배열을 생성
A = [1, 2, 3]
B = np.array(B)
B

array([1, 2, 3])

In [4]:
# 데이터 타입 지정
A = np.array([1, 2, 3], dtype=np.float64)
# A = np.array([1., 2., 3.]
print(A.dtype)

B = A.astype(np.int32)
print(B.dtype)

float64
int32


### numpy.ndarray 클래스 

In [5]:
A = np.array([
    [1,2,3],
    [4,5,6]
])
print('type(A):', type(A))
print('A.ndim:', A.ndim) # 배열을 구성하는 차원의 개수
print('A.shape:', A.shape) # 배열을 구성하는 차원의 개수와 차원별 크기 (튜플)
print('A.size:', A.size) # 배열에 있는 모든 원소의 개수 = shape의 원소를 모두 곱한 값
print('A.dtype:', A.dtype) # 배열 원소의 데이터 타입
print('A.itemsize:', A.itemsize) # 배열 원소 하나의 바이트 크기
print('A.data:', A.data) # 배열 원소를 실제로 저장하고 있는 버퍼

type(A): <class 'numpy.ndarray'>
A.ndim: 2
A.shape: (2, 3)
A.size: 6
A.dtype: int32
A.itemsize: 4
A.data: <memory at 0x000002FC4C162A80>


In [6]:
A = np.array([
    [1,2,3],
    [4,5,6]
])
print('A:', A)

print('A.max():', A.max()) # 최댓값
print('A.min():', A.min()) # 최솟값
print('A.sum():', A.sum()) # 총합
print('A.mean():', A.mean()) # 평균

print('==========☆==========')
# 계산할 차원 방향을 지정하여 계산
print('A.sum(axis=0):', A.sum(axis=0)) # 열 방향 계산
print('A.sum(axis=1):', A.sum(axis=1)) # 행 방향 계산

A: [[1 2 3]
 [4 5 6]]
A.max(): 6
A.min(): 1
A.sum(): 21
A.mean(): 3.5
==========☆==========
A.sum(axis=0): [5 7 9]
A.sum(axis=1): [ 6 15]


# 연속 원소 배열 생성 함수: arange()

In [7]:
A = np.arange(5) # 마지막값
B = np.arange(2, 5) # 시작값, 마지막값
C = np.arange(1, 10, 2) # 시작값, 마지막값, 간격
A, B, C

(array([0, 1, 2, 3, 4]), array([2, 3, 4]), array([1, 3, 5, 7, 9]))

### 3차원

In [8]:
A = np.arange(24) # 0부터 23까지 배열(list)
print(A)

print('==========☆reshape☆==========')

# reshape(열 방향, 열 방향 , 행 방향)
A = np.arange(24).reshape(2,3,4)
print(A)
# [
#     [[0,1,2,3],[4,5,6,7],[8,9,10,11]],
#     [[12,13,14,15],[16,17,18,19],[20,21,22,23]]
# ]

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
==========☆reshape☆==========
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [9]:
A = np.arange(10000).reshape(100,100)
# print(A)

# 생략 없이 프린트
import sys
np.set_printoptions(threshold=sys.maxsize)

# 배열 생성 함수
- zeros(())
- ones(())


In [10]:
A = np.zeros((2, 3)) # 모든 원소 0 (default=float64)
B = np.ones((2, 3)) # 모든 원소 1
C = np.empty((2, 3)) # 초기화되지 않도록 
D = np.random.random((2, 3)) # 0~1 사이의 무작위
E = np.random.randint(1, 10, (2, 3)) # 지정한 범위 내의 무작위
A, B, C, D, E

(array([[0., 0., 0.],
        [0., 0., 0.]]),
 array([[1., 1., 1.],
        [1., 1., 1.]]),
 array([[0., 0., 0.],
        [0., 0., 0.]]),
 array([[0.70764938, 0.04544483, 0.16533785],
        [0.16933168, 0.62636568, 0.99178586]]),
 array([[7, 3, 9],
        [9, 3, 8]]))

# 인덱싱(Indexing) & 슬라이싱(Slicing)

In [11]:
A = np.arange(1, 7).reshape(2, 3)

# 행벡터 출력
for row in A:
    print(row)
    
print('==========☆==========')

# 열벡터 출력
for col in A.T:
    print(col)
    
print('==========☆==========')

# 원소 개별 출력
for i in A.flat:
    print(i)

[1 2 3]
[4 5 6]
==========☆==========
[1 4]
[2 5]
[3 6]
==========☆==========
1
2
3
4
5
6


In [12]:
A = np.arange(1, 10).reshape(3,3)
print(A)
print(A[0, ...]) # 첫 번째 행 슬라이싱
print(A[..., 0]) # 첫 번째 열 슬라이싱

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3]
[1 4 7]
